apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  mongo.conf: |
    storage:
      dbPath: /data/db
    MONGO_INITDB_ROOT_USERNAME: admin
    UNBOUND_MONGO_HOST: mongodb
    UNBOUND_MONGO_PORT: "27017"
    UNBOUND_MONGO_USER: unbound
    UNBOUND_MONGO_DB: unboundLogDB